### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by ArmandRo** [Whimmey/BiliBiliTimer#8]
bilibili好像更新了，现在不能用了~o(╥﹏╥)o~

**Comment by Whimmey** [comment]
我刚刚还用呢，是下载的`Bili-extension-API.zip`吗？安装之后有刷新bilibili视频页面嘛

**Comment by ArmandRo** [comment]
之前2.1好像有点问题，换了3.0能用了

**Comment by ArmandRo** [comment]
谢谢
